In [6]:
# ============================================
# Customer & Sales Analytics
# Pandas + NumPy
# ============================================

import pandas as pd
import numpy as np


# 1. CSV files load karna
data1 = pd.read_csv("customer.csv")
data2 = pd.read_csv("sales.csv")





# 5. Customer + Sales merge
df = pd.merge(
    data1,
    data2,
    on="CustomerID",
    how="inner"
)





# 6. Total Sales calculate
df["Total_Sales"] = df["Quantity"] * df["Price"]

In [7]:
df

,CustomerID,CustomerName,City,Age,OrderID,Product,Category,Quantity,Price,OrderDate,Total_Sales
0,C01,Rahul,Indore,25,1001,Laptop,Electronics,1,60000,2026-01-05,60000
1,C01,Rahul,Indore,25,1003,Mouse,Accessories,3,800,2026-01-12,2400
2,C02,Amit,Bhopal,28,1002,Mobile,Electronics,2,25000,2026-01-08,50000
3,C02,Amit,Bhopal,28,1006,Mouse,Accessories,2,800,2026-02-15,1600
4,C03,Priya,Rewa,24,1004,Laptop,Electronics,1,60000,2026-02-02,60000
5,C03,Priya,Rewa,24,1008,Keyboard,Accessories,4,1500,2026-03-10,6000
6,C04,Neha,Jabalpur,30,1005,Keyboard,Accessories,2,1500,2026-02-10,3000
7,C05,Rohit,Indore,27,1007,Mobile,Electronics,1,25000,2026-03-03,25000
8,C05,Rohit,Indore,27,1012,Keyboard,Accessories,3,1500,2026-03-25,4500
9,C06,Pooja,Bhopal,26,1009,Laptop,Electronics,1,60000,2026-03-15,60000
10,C07,Arjun,Jabalpur,32,1010,Mobile,Electronics,1,25000,2026-03-18,25000
11,C08,Anjali,Rewa,23,1011,Mouse,Accessories,5,800,2026-03-20,4000

In [8]:
# 8. Highest Sales upar, Lowest Sales niche
df = df.sort_values(
    "Total_Sales",
    ascending=False
)

In [9]:
df

,CustomerID,CustomerName,City,Age,OrderID,Product,Category,Quantity,Price,OrderDate,Total_Sales
0,C01,Rahul,Indore,25,1001,Laptop,Electronics,1,60000,2026-01-05,60000
4,C03,Priya,Rewa,24,1004,Laptop,Electronics,1,60000,2026-02-02,60000
9,C06,Pooja,Bhopal,26,1009,Laptop,Electronics,1,60000,2026-03-15,60000
2,C02,Amit,Bhopal,28,1002,Mobile,Electronics,2,25000,2026-01-08,50000
10,C07,Arjun,Jabalpur,32,1010,Mobile,Electronics,1,25000,2026-03-18,25000
7,C05,Rohit,Indore,27,1007,Mobile,Electronics,1,25000,2026-03-03,25000
5,C03,Priya,Rewa,24,1008,Keyboard,Accessories,4,1500,2026-03-10,6000
8,C05,Rohit,Indore,27,1012,Keyboard,Accessories,3,1500,2026-03-25,4500
11,C08,Anjali,Rewa,23,1011,Mouse,Accessories,5,800,2026-03-20,4000
6,C04,Neha,Jabalpur,30,1005,Keyboard,Accessories,2,1500,2026-02-10,3000
1,C01,Rahul,Indore,25,1003,Mouse,Accessories,3,800,2026-01-12,2400
3,C02,Amit,Bhopal,28,1006,Mouse,Accessories,2,800,2026-02-15,1600